Repository PipocaAgil-Grupo-Bordo/ciclo-agil-mobile, pull requests merged in 2024-05, with the labels that each got.

#74 Cia 156 / Keep user logged in
  app.json
  babel.config.js
  package-lock.json
  package.json
  src/context/useUserToken.tsx
  src/pages/Login/SigninForm/index.tsx
  src/pages/SignUp/SignUpForm/index.tsx
  src/routes/auth.router.tsx
  src/routes/index.tsx
  src/routes/stack.routes.tsx
  src/routes/type.ts
  src/types/auth.ts
  src/types/context.ts
  src/utils/secureStoreHelper.ts
  src/utils/submitHelper.ts
  src/utils/tokenAuthHelper.ts
  tsconfig.json
Labels: Wating for reviews

#77 Cia 158/back icon missing
  src/components/BackArrow/index.tsx
  src/components/BackArrow/style.ts
  src/components/Header/index.tsx
  src/components/Header/style.ts
  src/pages/MenstrualInitialSettings/2-LastPeriod/index.tsx
  src/pages/ResetPassword/2-CodeRequest/Confirmation/index.tsx
  src/pages/ResetPassword/2-CodeRequest/Confirmation/style.ts
  src/pages/ResetPassword/2-CodeRequest/index.tsx
  src/pages/ResetPassword/2-CodeRequest/style.ts
  src/pages/ResetPassword/3-NewPassword/index.tsx
  src/pages/ResetPassword/3-NewPassword/style.ts
  src/routes/stack.routes.tsx
Labels: Wating for reviews

#76 cia-157 / Fix scroll getting out of sync
  src/components/ScrollPicker/RenderedContent/index.tsx
  src/components/ScrollPicker/RenderedContent/style.ts
  src/components/ScrollPicker/index.tsx
  src/components/ScrollPicker/style.ts
  src/pages/MenstrualInitialSettings/SharedComponents/Information/style.ts
Labels: Wating for reviews

#75 cia-135 / user header
  src/pages/Home/UserHeader/index.tsx
  src/pages/Home/UserHeader/style.ts
  src/pages/Home/index.tsx
  src/pages/Home/style.ts
Labels: Wating for reviews

#73 Cia 141 meu ciclo static
  assets/images/dropIcon.png
  src/pages/Home/CycleOverview/index.tsx
  src/pages/Home/CycleOverview/style.ts
  src/pages/Home/index.tsx
  src/routes/stack.routes.tsx
Labels: Wating for reviews

#79 cia 159 / Correct button style from password recovery screens
  src/components/GenericButton/index.tsx
  src/components/GenericButton/style.ts
  src/components/GenericButton/type.ts
  src/pages/ResetPassword/1-EmailRequest/ButtonsList/index.tsx
  src/pages/ResetPassword/2-CodeRequest/Buttons/index.tsx
  src/pages/ResetPassword/3-NewPassword/SubmitButtons/index.tsx
Labels: Wating for reviews

#84 cia 138 / cycle phase screen
  src/pages/Home/CyclePhase/index.tsx
  src/pages/Home/CyclePhase/style.ts
  src/pages/Home/index.tsx
Labels: Wating for reviews

#87 Update expo and its dependencies
  app.json
  package-lock.json
  package.json
Labels: Approved

#90 cia 165 / Wrong text in cycle overview
  src/pages/Home/CycleOverview/index.tsx
Labels: Wating for reviews

#85 cia 162 / back button not included in a few screens
  src/pages/Policy/index.tsx
  src/pages/Policy/style.ts
  src/pages/ResetPassword/1-EmailRequest/index.tsx
  src/pages/ResetPassword/1-EmailRequest/style.ts
  src/pages/SignUp/Header/index.tsx
  src/pages/SignUp/Header/style.ts
Labels: Wating for reviews

#88 cia 166 / Modal not appearing once password is changed
  src/pages/ResetPassword/3-NewPassword/index.tsx
Labels: Wating for reviews

#91 cia 171 / OS back button taking user to infinite loading screen
  src/pages/Login/index.tsx
Labels: Wating for reviews

#92 Cia 170 / button tap not firing when the keyboard is on screen
  src/pages/ResetPassword/3-NewPassword/index.tsx
Labels: Wating for reviews

#86 Addition of new typescript rules
  src/components/Form/index.tsx
  src/components/Form/style.tsx
  src/components/Form/type.ts
  src/pages/Home/CycleOverview/style.ts
  src/pages/MenstrualInitialSettings/3-CycleDuration/index.tsx
  src/pages/MenstrualInitialSettings/SharedComponents/Buttons/type.ts
  src/routes/auth.router.tsx
  tsconfig.json
Labels: Wating for reviews

#96 cia 161 / unnecessary period
  src/pages/MenstrualInitialSettings/2-LastPeriod/index.tsx
Labels: Wating for reviews

#97 cia 166 / missing exclamation mark
  src/pages/ResetPassword/3-NewPassword/index.tsx
Labels: Wating for reviews

#94 cia 137 / Cycle screen mini calendar
  src/pages/Home/MiniCalendar/CurrentMonth/index.tsx
  src/pages/Home/MiniCalendar/CurrentMonth/style.ts
  src/pages/Home/MiniCalendar/WeeklySection/index.tsx
  src/pages/Home/MiniCalendar/WeeklySection/style.ts
  src/pages/Home/MiniCalendar/index.tsx
  src/pages/Home/MiniCalendar/style.ts
  src/pages/Home/index.tsx
Labels: Wating for reviews

#93 cia 172 / cycle duration backend integration
  src/pages/MenstrualInitialSettings/3-CycleDuration/index.tsx
  src/services/menstrualApi.ts
  src/services/userApi.ts
  src/types/menstrual.ts
Labels: Wating for reviews

#95 cia 142 /my cycle statistics
  src/context/useUserToken.tsx
  src/pages/Home/CycleOverview/index.tsx
  src/pages/Home/MiniCalendar/WeeklySection/index.tsx
  src/services/userApi.ts
  src/types/auth.ts
  src/types/context.ts
  src/utils/dateHelpers.ts
  src/utils/setUserProfileHelper.ts
Labels: Work in progress
