Repository PipocaAgil-Grupo-Bordo/ciclo-agil-mobile, pull requests merged in 2024-12, with the labels that each got.

#134 cia-182: make bottom tab bar appear in the monthly calendar page
  package-lock.json
  package.json
  src/components/PageContainer/index.tsx
  src/components/PageContainer/style.ts
  src/pages/Analytics/index.tsx
  src/pages/Analytics/style.ts
  src/pages/AnualCalendar/CalendarBody/index.tsx
  src/pages/AnualCalendar/style.ts
  src/pages/Articles/index.tsx
  src/pages/Articles/style.ts
  src/pages/Home/UserHeader/index.tsx
  src/pages/Home/UserHeader/style.ts
  src/pages/Home/index.tsx
  src/pages/Home/style.ts
  src/pages/Login/SigninForm/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
  src/pages/MenstrualInitialSettings/2-LastPeriod/index.tsx
  src/pages/MenstrualInitialSettings/3-CycleDuration/index.tsx
  src/pages/MonthlyCalendar/CalendarApp/index.tsx
  src/pages/MonthlyCalendar/style.ts
  src/pages/SignUp/Header/style.ts
  src/pages/SignUp/SignUpForm/style.ts
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.ts
  src/pages/Team/index.tsx
  src/pages/Team/style.ts
  src/routes/auth.router.tsx
  src/routes/stack.routes.tsx
  src/routes/tab.routes.tsx
  src/routes/type.ts
  src/schemas/registerSchema.ts
  src/services/menstrualApi.ts
  src/services/userApi.ts
  src/styles/colors.ts
  src/types/auth.ts
Labels: Approved with conflicts

#131 feat: adding modal when future days are selected
  .gitignore
  src/pages/AnualCalendar/CalendarBody/index.tsx
  src/pages/MonthlyCalendar/CalendarApp/index.tsx
Labels: Wating for reviews

#135 fix: removing some things and adjusting the function again
  src/pages/AnualCalendar/CalendarBody/index.tsx
Labels: Has feedback

#141 cia-282-change-home-top-background
  assets/images/home-top-bg.png
  package-lock.json
  src/components/PageContainer/index.tsx
  src/components/PageContainer/style.ts
  src/pages/Home/HomeTopBackground/index.tsx
  src/pages/Home/HomeTopBackground/style.ts
  src/pages/Home/UserHeader/index.tsx
  src/pages/Home/index.tsx
  src/pages/Home/style.ts
Labels: Approved with conflicts

#143 Cia 283/changing mini calendar styling
  assets/images/CalendarIcon.svg
  src/pages/Home/MiniCalendar/CurrentMonth/index.tsx
  src/pages/Home/MiniCalendar/CurrentMonth/style.ts
  src/pages/Home/MiniCalendar/WeeklySection/index.tsx
  src/pages/Home/MiniCalendar/WeeklySection/style.ts
  src/pages/Home/MiniCalendar/style.ts
Labels: Wating for reviews
